version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8000:80
    environment:
    - DB_CONNECTION=mongodb
    - DB_HOST=mongodb
    - DB_PORT=27017
    - DB_DATABASE=mydatabase
    - DB_USERNAME=root
    - DB_PASSWORD=root
    volumes:
      - .:/var/www/html
    depends_on:
    - mongodb
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=mydatabase
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_URL=mongodb://root:root@mongodb:27017/
    depends_on:
    - mongodb
